// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview OSO Brain Scan feature to assess clarity, attention span, and stress level.
 *
 * - generateBrainFitnessReport - A function that generates the brain fitness report.
 * - BrainScanInput - The input type for the generateBrainFitnessReport function.
 * - BrainScanOutput - The return type for the generateBrainFitnessReport function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const BrainScanInputSchema = z.object({
  studentName: z.string().describe('The name of the student.'),
  clarityScore: z.number().describe('Student clarity score (0-100).'),
  attentionSpanScore: z.number().describe('Student attention span score (0-100).'),
  stressLevelScore: z.number().describe('Student stress level score (0-100).'),
  studyHours: z.number().describe('Number of hours spent studying per week.'),
  sleepHours: z.number().describe('Number of hours spent sleeping per night.'),
});
export type BrainScanInput = z.infer<typeof BrainScanInputSchema>;

const BrainScanOutputSchema = z.object({
  reportSummary: z.string().describe('A summary of the brain fitness report.'),
  recommendations: z.string().describe('Personalized recommendations for the student.'),
});
export type BrainScanOutput = z.infer<typeof BrainScanOutputSchema>;

export async function generateBrainFitnessReport(input: BrainScanInput): Promise<BrainScanOutput> {
  return brainScanFlow(input);
}

const brainScanPrompt = ai.definePrompt({
  name: 'brainScanPrompt',
  input: {schema: BrainScanInputSchema},
  output: {schema: BrainScanOutputSchema},
  prompt: `You are an AI assistant specializing in generating personalized brain fitness reports for students.

  Based on the student's scores for clarity, attention span, and stress level, along with their study and sleep habits, create a concise report summary and provide actionable recommendations.

  Student Name: {{{studentName}}}
  Clarity Score: {{{clarityScore}}}
  Attention Span Score: {{{attentionSpanScore}}}
  Stress Level Score: {{{stressLevelScore}}}
  Study Hours per Week: {{{studyHours}}}
  Sleep Hours per Night: {{{sleepHours}}}

  Report Summary:
  {{{reportSummary}}}

  Recommendations:
  {{{recommendations}}}
  `,
});

const brainScanFlow = ai.defineFlow(
  {
    name: 'brainScanFlow',
    inputSchema: BrainScanInputSchema,
    outputSchema: BrainScanOutputSchema,
  },
  async input => {
    const {output} = await brainScanPrompt(input);
    return output!;
  }
);
