
'use server';
/**
 * @fileOverview AI flow to generate an exam-style test series.
 *
 * - generateExamTest - A function that generates a list of questions for a given exam type/subject.
 * - GenerateExamTestInput - The input type for the function.
 * - GenerateExamTestOutput - The return type for the function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

// Base schema for a question, without refinement. This allows using .omit() etc.
const BaseQuestionSchema = z.object({
  questionType: z.enum(["mcq", "subjective"]).describe("The type of the question: 'mcq' for multiple-choice, 'subjective' for open-ended."),
  questionText: z.string().describe('The main text of the question. If a diagram is generated (see diagramDataUri), this text should refer to it (e.g., "Refer to the diagram above..."). Chemical formulas, reactions, or logical symbols must be represented in plain text (e.g., CH3-CH2-OH, A + B -> C, p AND q). No LaTeX or special formatting.'),
  
  // MCQ fields
  options: z.array(z.string()).length(4, { message: "MCQ must have exactly 4 options." }).optional(),
  correctAnswerIndex: z.number().min(0).max(3).optional(),
  
  // Subjective field
  modelAnswer: z.string().optional().describe("For subjective questions, a detailed model answer outlining the key points expected."),
  
  explanation: z.string().describe('A brief, clear explanation for the correct answer or model answer. This field is mandatory for all question types.'),
  diagramPrompt: z.string().optional().describe("A textual description of a diagram needed for this question (e.g., 'A simple series circuit with a battery, resistor, and switch.'). If no diagram is needed, omit this field. This prompt will be used to generate an image."),
  diagramDataUri: z.string().optional().describe("Data URI of the generated diagram image (e.g., 'data:image/png;base64,...'), if applicable and generated by the flow.")
});

// Final, refined schema for a question.
const QuestionSchema = BaseQuestionSchema.superRefine((data, ctx) => {
  if (data.questionType === 'mcq') {
    if (data.options === undefined) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "MCQs must have an 'options' array.",
        path: ["options"],
      });
    }
    if (data.correctAnswerIndex === undefined) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "MCQs must have a 'correctAnswerIndex'.",
        path: ["correctAnswerIndex"],
      });
    }
  }
  if (data.questionType === 'subjective') {
    if (data.modelAnswer === undefined) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        message: "Subjective questions must have a 'modelAnswer'.",
        path: ["modelAnswer"],
      });
    }
  }
});

const GenerateExamTestInputSchema = z.object({
  examNameOrType: z.string().describe('The name or type of the exam (e.g., "NEET UG", "JEE Main Physics", "Class 10 Science Prelim", "UPSC CSE Prelims GS Paper 1", "NEET SS Cardiology").'),
  subject: z.string().optional().describe('Specific subject for the test, if applicable (e.g., "Physics", "Organic Chemistry", "Indian Polity", "Cardiology").'),
  numQuestions: z.number().min(1).max(200).default(10).describe('The desired number of questions. For major exams, the AI will attempt to generate the standard number of questions for a full test unless a specific (lower) number is requested here.'),
  includeSubjective: z.boolean().optional().default(false).describe("Whether to include subjective (written-answer) questions."),
  subjectiveQuestionCount: z.number().min(1).optional().describe("If including subjective questions, specify how many. If omitted, AI will decide a reasonable mix based on the exam type."),
});
export type GenerateExamTestInput = z.infer<typeof GenerateExamTestInputSchema>;

const GenerateExamTestOutputSchema = z.object({
  testTitle: z.string().describe('A suitable title for the generated test (e.g., "NEET UG Physics Mini Mock Test", "JEE Main Full Syllabus Mock Test - Paper 1", "NEET SS Cardiology Mock Test"). This title MUST be generated and included.'),
  questions: z.array(QuestionSchema).describe('An array of generated questions.'),
});
export type GenerateExamTestOutput = z.infer<typeof GenerateExamTestOutputSchema>;

export async function generateExamTest(input: GenerateExamTestInput): Promise<GenerateExamTestOutput> {
  console.log(`[Genkit Flow Wrapper - generateExamTest] Generating test with input:`, JSON.stringify(input));
  const result = await generateExamTestFlow(input);
  console.log(`[Genkit Flow Wrapper - generateExamTest] Test generated. Title: "${result.testTitle}". Number of questions: ${result.questions.length}`);
  return result;
}

// This prompt is for generating the textual part of the questions.
// It will output a `diagramPrompt` if a question needs a visual.
const generateTextQuestionsPrompt = ai.definePrompt({
  name: 'generateTextQuestionsPrompt',
  input: {schema: GenerateExamTestInputSchema},
  output: {
    // Define a specific schema for this prompt's output, omitting the diagramDataUri.
    schema: z.object({
      testTitle: z.string().describe('A suitable title for the generated test (e.g., "NEET UG Physics Mini Mock Test", "JEE Main Full Syllabus Mock Test - Paper 1", "NEET SS Cardiology Mock Test"). This title MUST be generated and included.'),
      questions: z.array(BaseQuestionSchema.omit({ diagramDataUri: true })).describe('An array of generated questions without diagram data URI.'),
    }).required({ testTitle: true })
  },
  prompt: `You are an expert AI Test Generator for Indian competitive and school exams. Your output must be a JSON object that strictly adheres to the provided output schema.

**Key Generation Directives:**

1.  **Exam Fidelity:**
    *   **Question Count:** For major exams, you MUST generate the standard number of questions for a full test unless a smaller \`numQuestions\` is specified.
        *   **NEET UG:** 200 questions (50 each for Physics, Chem, Botany, Zoology).
        *   **JEE Main:** 90 questions (30 each for Physics, Chem, Maths).
        *   **UPSC CSE Prelims GS-1:** 100 questions.
        *   **NEET SS (e.g., Cardiology):** 100 questions for a full mock.
        *   **CAT Sections:** VARC (24), DILR (20), QA (22).
    *   **Pattern & Style:** Questions MUST mirror the latest known pattern, difficulty, and style of Previous Year Questions (PYQs) for the given \`examNameOrType\`.

2.  **Super-Specialty Exam Accuracy (Critical):**
    *   For postgraduate or super-specialty exams (e.g., "NEET SS Cardiology", "UPSC CSE Mains Optional"), questions must be of **EXPERT, SUPER-SPECIALIST DIFFICULTY**.
    *   These should be **lengthy, tough questions** often involving clinical vignettes, case scenarios, or deep analytical skills, mirroring the cognitive demand of the actual exam.
    *   **DO NOT ask foundational questions.** A "NEET SS Cardiology" question must challenge a practicing cardiologist, not an MBBS student.

3.  **Content & Formatting:**
    *   **Question Types:** If \`includeSubjective\` is true, generate a mix of MCQs and subjective questions as specified. Otherwise, all questions must be MCQs. MCQs require 4 options and a \`correctAnswerIndex\`. Subjective questions require a \`modelAnswer\`.
    *   **Calculations:** For numerical subjects (Physics, Maths, etc.), include a significant portion of calculation-based problems.
    *   **Explanations:** You MUST provide a clear, concise 'explanation' for every single question. This is not optional.
    *   **Diagrams:** For questions requiring a visual, include a \`diagramPrompt\` field with a clear, textual description of the diagram (e.g., "A pulley system with two masses..."). The \`questionText\` should refer to it.
    *   **Plain Text Only:** All text, including formulas (H2O, CH3-CH2-OH) and symbols (->, AND), must be plain text. No LaTeX or special formatting.

4.  **Final Output:**
    *   The root of the JSON output must contain two properties: \`testTitle\` (a descriptive title for the test) and \`questions\` (an array of question objects).

**Request Details:**
*   **Exam:** {{{examNameOrType}}}
*   **Subject:** {{#if subject}}{{{subject}}}{{else}}All subjects{{/if}}
*   **Requested Questions:** {{{numQuestions}}} (Adhere to standard exam counts for full mocks)

Generate the JSON test data now.
`,
});

const generateExamTestFlow = ai.defineFlow(
  {
    name: 'generateExamTestFlow',
    inputSchema: GenerateExamTestInputSchema,
    outputSchema: GenerateExamTestOutputSchema,
  },
  async (input) => {
    try {
      console.log(`[Genkit Flow - generateExamTestFlow] Starting test generation for: ${input.examNameOrType}, Subject: ${input.subject || 'N/A'}, Requested Qs: ${input.numQuestions}`);
      
      // Step 1: Generate textual content of questions, including diagram prompts
      const {output: textOutput} = await generateTextQuestionsPrompt(input);

      if (!textOutput || !textOutput.testTitle || !Array.isArray(textOutput.questions) || textOutput.questions.length === 0) {
          console.error("[Genkit Flow - generateExamTestFlow] AI failed to generate the initial test structure (text part). Output was null, malformed, or empty:", textOutput);
          // Return a valid empty structure if the AI completely fails
          return {
            testTitle: `Error Generating Test for ${input.examNameOrType}`,
            questions: [{
              questionType: "mcq",
              questionText: "Error: AI failed to generate questions for this test. The model might be overloaded or the request was too complex. Please try generating a smaller test or try again later.",
              options: ["N/A", "N/A", "N/A", "N/A"],
              correctAnswerIndex: 0,
              explanation: "The AI model could not produce the expected test content. This often happens with very large test requests (e.g., 200 questions) during peak times."
            }]
          };
      }
      console.log(`[Genkit Flow - generateExamTestFlow] Text part generated. Title: "${textOutput.testTitle}". Number of text questions: ${textOutput.questions.length}`);

      // Step 2: Iterate through questions and generate diagrams if diagramPrompt is present
      const questionsWithDiagrams = await Promise.all(
        textOutput.questions.map(async (question: any) => { 
          if (question.diagramPrompt && typeof question.diagramPrompt === 'string' && question.diagramPrompt.trim() !== "") {
            console.log(`[Genkit Flow - generateExamTestFlow] Diagram prompt found for question: "${question.questionText.substring(0,30)}...". Prompt: "${question.diagramPrompt}"`);
            try {
              const {media} = await ai.generate({
                model: 'googleai/gemini-2.0-flash-preview-image-generation',
                prompt: `Generate a clear, simple diagram suitable for a multiple-choice question based on this description: ${question.diagramPrompt}. The diagram should visually represent the key elements needed to understand the question. Avoid text in the diagram unless absolutely necessary for labels.`,
                config: {
                  responseModalities: ['TEXT', 'IMAGE'], 
                },
              });
              console.log(`[Genkit Flow - generateExamTestFlow] Diagram generated for: "${question.diagramPrompt.substring(0,30)}...". Media URL available.`);
              return { 
                ...question, 
                diagramDataUri: media?.url,
                diagramPrompt: undefined 
              } as z.infer<typeof QuestionSchema>;
            } catch (imgError) {
              console.error(`[Genkit Flow - generateExamTestFlow] Failed to generate diagram for question "${question.questionText.substring(0,30)}...":`, imgError);
              return { ...question, diagramPrompt: undefined, diagramDataUri: undefined } as z.infer<typeof QuestionSchema>; 
            }
          }
          return { ...question, diagramPrompt: undefined, diagramDataUri: undefined } as z.infer<typeof QuestionSchema>;
        })
      );
      
      const finalOutput: GenerateExamTestOutput = {
        testTitle: textOutput.testTitle, // Ensured by fallback
        questions: questionsWithDiagrams,
      };

      console.log(`[Genkit Flow - generateExamTestFlow] Test Generation Complete. Title: "${finalOutput.testTitle}". Total questions processed: ${finalOutput.questions.length}. Questions with diagrams generated (attempted): ${finalOutput.questions.filter(q => q.diagramDataUri).length}`);
      return finalOutput;
    } catch (error: any) {
      console.error(`[Genkit Flow - generateExamTestFlow] A critical error occurred during test generation for "${input.examNameOrType}":`, error);
      // This will be caught by the front-end and displayed to the user.
      throw new Error("The AI model is currently overloaded. This can happen with large or complex test requests. Please try again in a moment, or generate a smaller test.");
    }
  }
);
