
// src/types/weekly-studyport-report.ts

// Note: If using Firebase JS SDK v9+, Timestamp would be imported from 'firebase/firestore'
// import type { Timestamp } from 'firebase/firestore';

/**
 * Represents a weekly summary report of a student's activity in OSO StudyPort™.
 * These reports are auto-generated by a backend process (e.g., Firebase Cloud Function).
 */
export interface WeeklyStudyPortReport {
  /** Auto-generated unique ID for the report document. */
  report_id: string;

  /** Unique student identifier, referencing smart_ids.student_id. */
  student_id: string;

  /** Name of the student (denormalized for easier display in reports). */
  student_name: string;

  /** The start date of the week this report covers (e.g., Monday).
   *  Stored as a JavaScript Date object, converted to Firestore Timestamp on save.
   */
  week_start_date: Date;

  /** The end date of the week this report covers (e.g., Sunday).
   *  Stored as a JavaScript Date object, converted to Firestore Timestamp on save.
   */
  week_end_date: Date;

  /** Total number of StudyPort™ sessions the student had during this week. */
  total_sessions: number;

  /** Total time spent in StudyPort™ in minutes during this week. */
  total_minutes: number;

  /** Average focus level observed or assessed during the week (e.g., "High", "Medium", "Low", or a numeric score). */
  average_focus?: string | null;

  /** Average clarity status or observed improvement during the week (e.g., "Improved", "Consistent", "Needs Attention"). */
  average_clarity?: string | null;

  /** Array of summarized notes or key feedback points from StudyPort Admins during the week. */
  admin_notes?: string[] | null;

  /** Contact information for the parent (denormalized for sending notifications). */
  parent_contact: string;

  /** Status of the report notification delivery to the parent. */
  sent_status: 'pending' | 'sent' | 'failed';

  /** Timestamp indicating when this report document was created.
   *  Stored as a JavaScript Date object, converted to Firestore Timestamp on save.
   */
  created_at: Date;
}

